.TH "include/zroc/memory Directory Reference" 3 "Version 0.01" "ZroC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/zroc/memory Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBzroc_mem_sizes\&.h\fP"
.br
.ti -1c
.RI "file \fBzroc_memory\&.h\fP"
.br
.RI "Memory allocation wrappers with error checking\&. "
.in -1c
