.TH "include/zroc/base_types.h" 3 "Version 0.01" "ZroC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/zroc/base_types.h
.SH SYNOPSIS
.br
.PP
\fR#include <stdbool\&.h>\fP
.br
\fR#include <stddef\&.h>\fP
.br
\fR#include <stdint\&.h>\fP
.br

.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef uint8_t \fBu8\fP"
.br
.ti -1c
.RI "typedef int8_t \fBi8\fP"
.br
.ti -1c
.RI "typedef uint16_t \fBu16\fP"
.br
.ti -1c
.RI "typedef int16_t \fBi16\fP"
.br
.ti -1c
.RI "typedef uint32_t \fBu32\fP"
.br
.ti -1c
.RI "typedef int32_t \fBi32\fP"
.br
.ti -1c
.RI "typedef uint64_t \fBu64\fP"
.br
.ti -1c
.RI "typedef int64_t \fBi64\fP"
.br
.ti -1c
.RI "typedef size_t \fBusize\fP"
.br
.ti -1c
.RI "typedef ptrdiff_t \fBisize\fP"
.br
.ti -1c
.RI "typedef float \fBf32\fP"
.br
.ti -1c
.RI "typedef double \fBf64\fP"
.br
.ti -1c
.RI "typedef bool \fBboolean\fP"
.br
.ti -1c
.RI "typedef const char * \fBcstr\fP"
.br
.ti -1c
.RI "typedef \fBu8\fP \fBbyte\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef bool \fBboolean\fP"

.SS "typedef \fBu8\fP \fBbyte\fP"

.SS "typedef const char* \fBcstr\fP"

.SS "typedef float \fBf32\fP"

.SS "typedef double \fBf64\fP"

.SS "typedef int16_t \fBi16\fP"

.SS "typedef int32_t \fBi32\fP"

.SS "typedef int64_t \fBi64\fP"

.SS "typedef int8_t \fBi8\fP"

.SS "typedef ptrdiff_t \fBisize\fP"

.SS "typedef uint16_t \fBu16\fP"

.SS "typedef uint32_t \fBu32\fP"

.SS "typedef uint64_t \fBu64\fP"

.SS "typedef uint8_t \fBu8\fP"

.SS "typedef size_t \fBusize\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for ZroC from the source code\&.
