.TH "build/CMakeFiles/4.1.1/CompilerIdC/CMakeCCompilerId.c" 3 "Version 0.01" "ZroC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
build/CMakeFiles/4.1.1/CompilerIdC/CMakeCCompilerId.c
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__has_include\fP(x)"
.br
.ti -1c
.RI "#define \fBCOMPILER_ID\fP   ''"
.br
.ti -1c
.RI "#define \fBSTRINGIFY_HELPER\fP(X)"
.br
.ti -1c
.RI "#define \fBSTRINGIFY\fP(X)"
.br
.ti -1c
.RI "#define \fBPLATFORM_ID\fP"
.br
.ti -1c
.RI "#define \fBARCHITECTURE_ID\fP"
.br
.ti -1c
.RI "#define \fBDEC\fP(n)"
.br
.ti -1c
.RI "#define \fBHEX\fP(n)"
.br
.ti -1c
.RI "#define \fBC_STD_99\fP   199901L"
.br
.ti -1c
.RI "#define \fBC_STD_11\fP   201112L"
.br
.ti -1c
.RI "#define \fBC_STD_17\fP   201710L"
.br
.ti -1c
.RI "#define \fBC_STD_23\fP   202311L"
.br
.ti -1c
.RI "#define \fBC_VERSION\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "char const  * \fBinfo_compiler\fP = 'INFO' ':' 'compiler[' COMPILER_ID ']'"
.br
.ti -1c
.RI "char const  * \fBinfo_platform\fP = 'INFO' ':' 'platform[' PLATFORM_ID ']'"
.br
.ti -1c
.RI "char const  * \fBinfo_arch\fP = 'INFO' ':' 'arch[' ARCHITECTURE_ID ']'"
.br
.ti -1c
.RI "const char * \fBinfo_language_standard_default\fP"
.br
.ti -1c
.RI "const char * \fBinfo_language_extensions_default\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define __has_include( x)"
\fBValue:\fP
.nf
0
.PP
.fi

.SS "#define ARCHITECTURE_ID"

.SS "#define C_STD_11   201112L"

.SS "#define C_STD_17   201710L"

.SS "#define C_STD_23   202311L"

.SS "#define C_STD_99   199901L"

.SS "#define C_VERSION"

.SS "#define COMPILER_ID   ''"

.SS "#define DEC( n)"
\fBValue:\fP
.nf
  ('0' + (((n) / 10000000)%10)), \\
  ('0' + (((n) / 1000000)%10)),  \\
  ('0' + (((n) / 100000)%10)),   \\
  ('0' + (((n) / 10000)%10)),    \\
  ('0' + (((n) / 1000)%10)),     \\
  ('0' + (((n) / 100)%10)),      \\
  ('0' + (((n) / 10)%10)),       \\
  ('0' +  ((n) % 10))
.PP
.fi

.SS "#define HEX( n)"
\fBValue:\fP
.nf
  ('0' + ((n)>>28 & 0xF)), \\
  ('0' + ((n)>>24 & 0xF)), \\
  ('0' + ((n)>>20 & 0xF)), \\
  ('0' + ((n)>>16 & 0xF)), \\
  ('0' + ((n)>>12 & 0xF)), \\
  ('0' + ((n)>>8  & 0xF)), \\
  ('0' + ((n)>>4  & 0xF)), \\
  ('0' + ((n)     & 0xF))
.PP
.fi

.SS "#define PLATFORM_ID"

.SS "#define STRINGIFY( X)"
\fBValue:\fP
.nf
STRINGIFY_HELPER(X)
.PP
.fi

.SS "#define STRINGIFY_HELPER( X)"
\fBValue:\fP
.nf
#X
.PP
.fi

.SH "Function Documentation"
.PP 
.SS "int main (int argc, char * argv[])"

.SH "Variable Documentation"
.PP 
.SS "char const* info_arch = 'INFO' ':' 'arch[' ARCHITECTURE_ID ']'"

.SS "char const* info_compiler = 'INFO' ':' 'compiler[' COMPILER_ID ']'"

.SS "const char* info_language_extensions_default"
\fBInitial value:\fP
.nf
= "INFO" ":" "extensions_default["





  "OFF"

"]"
.PP
.fi

.SS "const char* info_language_standard_default"
\fBInitial value:\fP
.nf
=
  "INFO" ":" "standard_default[" C_VERSION "]"
.PP
.fi

.SS "char const* info_platform = 'INFO' ':' 'platform[' PLATFORM_ID ']'"

.SH "Author"
.PP 
Generated automatically by Doxygen for ZroC from the source code\&.
