.TH "md_README" 3 "Version 0.01" "ZroC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_README \- zroc 
.PP


.PP
ZroC, Collection of useful C libraries
.SH "Errors"
.PP
.IP "\(bu" 2
Error types via enum
.IP "\(bu" 2
Type to string
.PP
.SH "Logging"
.PP
.IP "\(bu" 2
Simple logging with formatting
.PP
.SH "Memory"
.PP
.IP "\(bu" 2
Simple malloc, calloc, realloc, free wrappers
.IP "\(bu" 2
Wrap basics with basic validation and check for success
.PP
.SH "Data Structures"
.PP
.IP "\(bu" 2
Array
.IP "\(bu" 2
Dynamic Array
.IP "\(bu" 2
Stack
.IP "\(bu" 2
Queue
.IP "\(bu" 2
Ring Buffer
.IP "\(bu" 2
Linked List (Doubly)
.IP "\(bu" 2
Hash Map
.IP "\(bu" 2
BST
.IP "\(bu" 2
Quad/Oct Tree
.IP "\(bu" 2
Red/Black Tree
.IP "\(bu" 2
Heap(Min / Max)
.IP "\(bu" 2
Graph
.PP
.SH "Algorithms"
.PP
.IP "\(bu" 2
Merge Sort
.IP "\(bu" 2
Quick Sort
.IP "\(bu" 2
Bubble Sort
.PP
.SH "Math"
.PP
.IP "\(bu" 2
Vectors
.IP "  \(bu" 4
2D, 3D
.IP "  \(bu" 4
add, sub, mult, div
.IP "  \(bu" 4
dot product
.IP "  \(bu" 4
scaling (multiply by scalar)
.PP

.IP "\(bu" 2
Matrices
.IP "  \(bu" 4
mat2, mat3, mat4
.IP "  \(bu" 4
invert, determinant, transpose
.IP "  \(bu" 4
add, sub, mult, div
.PP

.IP "\(bu" 2
Constants
.IP "  \(bu" 4
Epsilon
.IP "  \(bu" 4
Pi
.IP "  \(bu" 4
DegreeToRadian
.IP "  \(bu" 4
RadianToDegree 
.PP

.PP

