.TH "tests/test_log.c" 3 "Version 0.01" "ZroC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tests/test_log.c
.SH SYNOPSIS
.br
.PP
\fR#include <criterion/criterion\&.h>\fP
.br
\fR#include <criterion/internal/assert\&.h>\fP
.br
\fR#include <stdio\&.h>\fP
.br
\fR#include <time\&.h>\fP
.br
\fR#include <zroc/log/zroc_log\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTest\fP (log, default_logger_to_file)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "Test (log , default_logger_to_file )"

.SH "Author"
.PP 
Generated automatically by Doxygen for ZroC from the source code\&.
