.TH "tests/test_error.c" 3 "Version 0.01" "ZroC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tests/test_error.c
.SH SYNOPSIS
.br
.PP
\fR#include <criterion/criterion\&.h>\fP
.br
\fR#include <zroc/zroc\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTest\fP (error, err_str_returns_string)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "Test (error , err_str_returns_string )"

.SH "Author"
.PP 
Generated automatically by Doxygen for ZroC from the source code\&.
